name: Deploy to GitHub Pages
on:
  # push:
  #   branches:
  #     - development
  schedule:
    - cron: '0 7 * * *' # 2am ET
    - cron: '8 16 * * *' # 11:08am ET
    # - cron: '0 18 * * *' # 1pm ET

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build
      env:
        GITHUB_KEY: ${{ secrets.GITHUB_KEY }}
        GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
        INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
        INSTAGRAM_GRAPH_TOKEN: ${{ secrets.INSTAGRAM_GRAPH_TOKEN }}
        INSTAGRAM_TOKEN_REFRESH: ${{ secrets.INSTAGRAM_TOKEN_REFRESH }}
        INSTAGRAM_TOKEN_EXPIRE: ${{ secrets.INSTAGRAM_TOKEN_EXPIRE }}
        INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
        LETTERBOXD_USERNAME: ${{ secrets.LETTERBOXD_USERNAME }}
        LETTERBOXD_PASSWORD: ${{ secrets.LETTERBOXD_PASSWORD }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: dist
