name: GitHub Pages deployment
on:
  push:
    branches:
      - development
  schedule:
    - cron: '0 6 * * 1,4' # 2am ET on Monday and Thursday
    # - cron: '12 15 * * *' # 11:12am ET
    # - cron: '0 17 * * *' # 1pm ET
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build
      env:
        GH_KEY: ${{ secrets.GH_KEY }}
        GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
        LETTERBOXD_USERNAME: ${{ secrets.LETTERBOXD_USERNAME }}
        LETTERBOXD_PASSWORD: ${{ secrets.LETTERBOXD_PASSWORD }}
        G_PHOTOS_CLIENT_ID: ${{ secrets.G_PHOTOS_CLIENT_ID }}
        G_PHOTOS_CLIENT_SECRET: ${{ secrets.G_PHOTOS_CLIENT_SECRET }}
        G_PHOTOS_REFRESH_TOKEN: ${{ secrets.G_PHOTOS_REFRESH_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: dist
