name: Deploy to GitHub Pages
on:
  # push:
    # branches:
    #   - development
  schedule:
    - cron: '0 2 * * *'
    - cron: '40 19 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
        INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
        LETTERBOXD_USERNAME: ${{ secrets.LETTERBOXD_USERNAME }}
        LETTERBOXD_PASSWORD: ${{ secrets.LETTERBOXD_PASSWORD }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: dist
